#+STARTUP: indent

#+OPTIONS: num:nil toc:nil reveal_history:t
#+PROPERTY: header-args :eval no-export

#+include: reveal_header.org :minlevel 1

#+Title: The Road to Reality

* The Road to Reality

Interactive Physics from Eval to Einstein

* Abstract
#+begin_notes
The story of our current best understanding of physical reality is a fascinating
human tale. Over many centuries, intuitive physics and philosophical theories
were subjected to the crucible of the scientific method, and the mathematical
models and tools that survived are both eerily beautiful and unreasonably
effective at predicting the evolution of the physical world.

Unfortunately, understanding this story and its mathematical models typically
requires years of mathematical training, and a special type of brain that's able
to process dense abstraction with very few visual clues. This is a tragedy, as
understanding these physical models at a deep level is a prerequisite to many of
the solutions for the huge issues our world is facing.

This talk will present SICMUtils, a Clojure system designed as a workshop for
conducting serious work in mathematical physics and sharing those explorations
in a deeply interactive, multiplayer way. The library is built as a "literate
program" in a layered style that recapitulates the story of modern physics; a
major goal is to rebuild a modern scientific computing stack out primitives as
elegant and understandable as the models they implement.
#+end_notes

* Notes
#+begin_notes
#+end_notes


Missing from either talk:

- the library

* Project Intro

SICMUtils, modeled after Road to Reality...

The narrative structure of that books is the story of humans coming to terms
with the fact that physical reality can be modeled.

The signs were all around, since that’s what language does for us; we can make,
we have a model in our heads; but we don’t think of that as abstraction.

* What is Physics?

What is physics? Classical Mechanics is Geometry + algebra; I see thins; I can
turn the algebraic crank — and the numbers reflect the /new/ reality out there.

**So something computational seems to be happening.**

* Following Elegance leads to Results

* Buildup to Complex Numbers

Example of simple things having complex results.

* Autodiff, Dual Numbers

* Quaternions

give up commutative property...

* Aesthetics lead the game

Then you go from the above to a sort of all in trust of the aesthetic sense!
Following the math, Dirac, etc... Cool.

* NOT so with scientific computing!

And what has NOT seemingly happened is that we’ve decomposed scientific
computing into elegant primitives that we can apply.

(LEAD IN to stuff from the other talks?)

* On the other side, Mathbox

Explorables!

* Short Version of Lagrange Example...

* THEN THINK on what should come next.

Probably the "why is this important" needs to happen here too.
